[forest]
trees = ["trees" ]  # The directories in which your trees are stored
assets = ["assets"] # The directories in which your assets are stored
url = "https://cosmos-1989.github.io/math-blog/" # GitHub Pages URL
